use_frameworks!

install! 'cocoapods', deterministic_uuids: false
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

# - https://repo.backbase.com/api/pods/ios3/ (backbase-pods3)
# - https://repo.backbase.com/api/pods/ios-identity/ (backbase-pods-identity)
# - https://repo.backbase.com/api/pods/ios-business/ (backbase-pods-business)

plugin 'cocoapods-art', sources: [
  'backbase-pods3',
  'backbase-pods-business',
  'backbase-pods-identity',
  'backbase-pods-retail3'
]

target 'BusinessContactsManagerJourneyExtended_Example' do
  pod 'BusinessContactsManagerJourneyExtended', :path => '../'
  pod 'BusinessJourneyCommon', '~> 2.0'
  pod 'BackbaseObservability', '~> 1.0'
  pod 'FlagKit'
  pod 'Resolver', '~> 1.2.1'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SwiftLint'
  pod 'BackbaseIdentity'
  pod 'BusinessWorkspacesJourney', '3.0.0'
  pod 'BusinessWorkspacesJourneyWorkspacesUseCase2', '3.0.0'
  pod 'IdentityAuthenticationJourney', '~> 3.0'

  target 'BusinessContactsManagerJourneyExtended_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      # Our frameworks are built with library evolution support enabled,
      # and they are linked against dependencies with the same setting.
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'

      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
      if config.name == 'Release'
        cflags << '-fembed-bitcode'
        config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      else
        cflags << '-fembed-bitcode-marker'
        config.build_settings['BITCODE_GENERATION_MODE'] = 'marker'
      end

      config.build_settings['OTHER_CFLAGS'] = cflags
    end
  end
  update_vg_parallax_pod()
end

# Temporary fix for this dependency to import correctly one of it's subdependencies
def update_vg_parallax_pod
  filename = [Dir.pwd, "Pods", "VGParallaxHeader", "VGParallaxHeader", "UIScrollView+VGParallaxHeader.m"].join("/")
  File.chmod(0700, filename)
  text = File.read(filename)
  new_contents = text.gsub("#import <PureLayout.h>", "#import <PureLayout/PureLayout.h>")
  File.open(filename, "w") {|file| file.puts new_contents }
end
