use_frameworks!

platform :ios, '10.0'

target 'BusinessContactsManagerJourneyExtended_Example' do
  pod 'BusinessContactsManagerJourneyExtended', :path => '../'

  target 'BusinessContactsManagerJourneyExtended_Tests' do
    inherit! :search_paths

    
  end
end
